name: CI/CD
on:
  push:
    branches:
      - main
  pull_request: {}
jobs:
  lint-and-test:
    name: Lint and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: npm
      - name: Download dependencies
        run: npm install
      - name: Lint
        run: npm run lint
